# ============================================================
#  Dovecot — Authentification (10-auth.conf)
#  SecureHealth-Net
# ============================================================

# Désactiver l'authentification en texte clair sans TLS
disable_plaintext_auth = yes

# Mécanismes d'authentification autorisés
auth_mechanisms = plain login

# Authentification par fichier de mots de passe
# (format : utilisateur:{PLAIN}motdepasse ou {SHA512-CRYPT}hash)
passdb {
    driver = passwd-file
    args = /etc/dovecot/users.passwd
}

# Base de données des utilisateurs
# Chemin aligné avec la livraison virtuelle Postfix : /var/mail/domaine/user/
userdb {
    driver = static
    args = uid=mail gid=mail home=/var/mail/%d/%n
}


# Socket d'authentification interne (conteneur isolé)
service auth {
    unix_listener auth-userdb {
        mode = 0600
    }
}
