# ============================================================
#  Dovecot — Configuration des boîtes mail (10-mail.conf)
#  SecureHealth-Net
# ============================================================

# Format de stockage des mails : Maildir (un fichier par mail)
# Plus fiable que mbox pour une infrastructure médicale
mail_location = maildir:/var/mail/%d/%n/Maildir

# Namespace de la boîte mail
namespace inbox {
    inbox = yes
    separator = /

    # Dossiers standards visibles dans Roundcube
    mailbox Drafts {
        special_use = \Drafts
        auto = subscribe
    }
    mailbox Envoyés {
        special_use = \Sent
        auto = subscribe
    }
    mailbox Corbeille {
        special_use = \Trash
        auto = subscribe
    }
    mailbox Indésirables {
        special_use = \Junk
        auto = subscribe
    }
}

# Permissions des fichiers mail
mail_privileged_group = mail
