# ============================================================
#  Dovecot — Configuration principale
#  SecureHealth-Net
# ============================================================

# Protocoles activés
protocols = imap lmtp

# Charger les fichiers de conf supplémentaires
!include conf.d/*.conf

# Logs vers stdout (Docker)
log_path = /dev/stdout
info_log_path = /dev/stdout
